# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff33b65aba3fa5343d91d8e6996f406d22b2ea22536483b21416f347c37e5ad9a7eee60039cbc3ae18d3bbef91cc45a6a3df17f54928c9ef578792783c3869b

test:
  secret_key_base: 4e689a9f2a4f41f176d8356672387941be78379c00455eb6e8a4f8e749bc6a1ea48ea379d36a253518a8a264f6c35aba156585e6104d81e0a26e399cd1e1278a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
