#!/bin/bash 

# Launch an nginx container, available on Docker Hub, as a background task. It
# should be named overlord, be able to restart on its own, and have its 80 port
# attached to the 5000 port of Char. You can check that your container functions
# properly by visiting
# http://<ip-de-char>:5000 on your web browser.

docker run --restart always --name overlord -d -p 5000:80 nginx

# https://blog.docker.com/2015/04/tips-for-deploying-nginx-official-image-with-docker/
# https://www.techrepublic.com/article/how-to-run-nginx-as-a-docker-container/
# https://docs.docker.com/config/containers/start-containers-automatically/
# docker stop <container name eg 546f7912f6ad>
# docker rm <container name>
# docker ps -a