#!/bin/bash

# Launch a mysql container as a background task. It should be able to restart on its
# own in case of error, and the root password of the database should be Kerrigan.
# You will also make sure that the database is stored in the hatchery volume, that
# the container directly creates a database named zerglings, and that the container
# itself is named spawning-pool.

docker run --name spawning-pool --restart on-failure -v hatchery -e MYSQL_ROOT_PASSWORD=Kerrigan -e MYSQL_DATABASE=zerglings -d mysql

# http://blog.arungupta.me/docker-mysql-persistence/
# https://docs.docker.com/samples/library/mysql/
# https://blog.codeship.com/ensuring-containers-are-always-running-with-dockers-restart-policy/