#!/bin/bash

# Launch a wordpress container as a background task, just for fun. The container
# should be named lair, its 80 port should be bound to the 8080 port of the virtual
# machine, and it should be able to use the spawning-pool container as a database
# service. You can try to access lair on your machine via a web browser, with the
# IP address of the virtual machine as a URL.
# Congratulations, you just deployed a functional Wordpress website in two commands!

#docker run --name lair --link spawning-pool:mysql -p 8080:80  -d wordpress
docker run --name lair --link spawning-pool -p 8080:80 -d wordpress

# http://www.deploycontainers.com/2017/12/29/running-wordpress-mysql-docker-containers/
# https://stackoverflow.com/questions/34620695/docker-what-is-the-equivalent-of-the-legacy-link-parameter
# --link may be deprecated and replaced with --net
# docker run --name lair --net=spawning-pool:mysql -p 8080:80  -d wordpress
